### ISSUE TITLE
Lab hack: symlinks

### ISSUE THREAD

**Issue by kelly-sovacool** [SchlossLab/schlosslab.github.io#34]
# Symlinks

Use symlinks to save time typing paths to directories you use frequently. For example, when you `ssh` into the HPC, your working directory is initially your home directory (`/home/uniqname/`). But we keep our project files in a shared lab drive: `/nfs/turbo/schloss-lab/`. You may be actively working on a project in `/nfs/turbo/schloss-lab/uniqname/project_name/` -- that can be long and hard to remember. To save time, you can create a `symlink` to your the project in your home directory like so:

```
ln -s /nfs/turbo/schloss-lab/uniqname/project_name/ /home/uniqname/project_name/
```

Then when you log in, you can simply type `cd project_name` to get to the project directory without typing the whole path.

**Comment by pschloss** [comment]
do you prefer symlinks to aliases? i put something like...

```
alias scfa='cd /nfs/turbo/schloss-lab/pschloss/Sze_SCFACRC_XXXX_2019'
```

into my `~/.bashrc` file. Then I can do...

```
$ scfa
```

and it moves me to that directory

**Comment by kelly-sovacool** [comment]
I do prefer symlinks because they show up with `ls` and act like regular paths for commands besides `cd`, such as in a script.
